name: BUILD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm ci

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
        # Required mail server address:
          server_address: smtp.gmail.com
        # Required mail server port:
          server_port: 465
        # Optional (recommended): mail server username:
          username: ${{secrets.MAIL_USERNAME}}
        # Optional (recommended) mail server password:
          password: ${{secrets.MAIL_PASSWORD}}
        # Required mail subject:
          subject: Github Actions job result
        # Required recipients' addresses:
          to: pamis73617@error57.com
        # Required sender full name (address can be skipped):
          from: ci@libLookup.com
        # Optional whether this connection use TLS (default is true if server_port is 465)
          secure: true
        # Optional plain body:
          body: Build job of ${{github.repository}} completed successfully!
        # Optional HTML body read from file:
          html_body: file://README.html
